# Site settings
title: Non-Profit Open Data Collective
description: "npodc.github.io"
url: "npodc.github.io"
author:
  name: "Ben Cipollini"
  email: "bcipollini@classy.org"
  url: "npodc.github.io"

# Build settings
baseUrl: ""  # this must be line 11; see circle_urls.sh
markdown: kramdown
source: .
destination: ./_site  # this must be line 14; see circle_urls.sh
permalink: "/:title"
paginate: 8
paginate_path: /page:num/

# Custom variables
version: "1.1.0"
currentYear: "2017"
googleanalytics: "UA-104155364-1"
blogUrl: "#"

# SEO
logo: /img/npodc-logo.png
authorTwitter: 'nipyorg'
gems:
  - jekyll-seo-tag
  - jekyll-paginate


# Options
reverse: true

collections:
  packages:
    output: true
    permalink: /packages/:path/index.html
